/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastros;

/**
 *
 * @author Adriano Silva
 */
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Date;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.conexao;
import javax.swing.text.MaskFormatter;
public final class cad_funcionarios extends javax.swing.JFrame {
    
    MaskFormatter formatoCpf,formatoCep,formatoFone,formatoDataNasc,formatoDataCad,formatoRg;
    int navega = 0;
    int inicia_combo =0;
    String ordenacao="nome",sexo="M";
    boolean primeiraVezCidade=true,primeiraVezBairro=true,primeiraVezLog=true;
    conexao con_usuarios,con_cidade,con_bairro,con_logradouro;
    
    
    public cad_funcionarios() {
        
        initComponents();
        
        setIcon();
        
        con_usuarios = new conexao();
        con_usuarios.conecta();
        
        con_cidade = new conexao();
        con_cidade.conecta();
        
        con_logradouro = new conexao();
        con_logradouro.conecta();
        
        con_bairro = new conexao();
        con_bairro.conecta();
        
        con_usuarios.executeSQL("select * from cliente order by "+ordenacao);
        con_cidade.executeSQL("select * from cidade order by nome");
        con_bairro.executeSQL("select * from bairro order by nome");
        con_logradouro.executeSQL("select * from logradouro order by nome");  
       
        try
        {
            while(con_cidade.resultset.next())
                cb_cidade.addItem(con_cidade.resultset.getString("nome"));
            while(con_bairro.resultset.next())
                cb_bairro.addItem(con_bairro.resultset.getString("nome"));
            while(con_logradouro.resultset.next())
                cb_logradouro.addItem(con_logradouro.resultset.getString("nome"));
         // while (con_usuarios.resultset.next())
          //jcb_pesquisa.addItem(con_usuarios.resultset.getString("nome"));
            
            atualiza_combo_box_cliente();
            con_usuarios.resultset.first();
            mostrar_dados();
           // tf_codigo.setText(con_usuarios.resultset.getString("codigo"));
           //tf_endereco.setText(con_usuarios.resultset.getString("nome"));
           //cb_cidade.setSelectedItem(con_usuarios.resultset.getString("uf"));
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }  
        
        preencher_jtable();//chama metod para preencher a Tabela das Cidades
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_ordenacao = new javax.swing.ButtonGroup();
        grupo_sexo = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        cb_logradouro = new javax.swing.JComboBox();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        botão_gravar = new javax.swing.JButton();
        botao_inserir = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tf_pesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcb_pesquisa = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rb_codigo = new javax.swing.JRadioButton();
        rb_nome = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        tf_codLog = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_complemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_codBairro = new javax.swing.JTextField();
        cb_bairro = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tf_codCidade = new javax.swing.JTextField();
        cb_cidade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        try
        {
            formatoCep = new MaskFormatter("##.###-###");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir o número de Telefone Celular"+erro);
        }
        tf_cep = tf_cep = new JFormattedTextField(formatoCep);
        jLabel12 = new javax.swing.JLabel();
        try
        {
            formatoRg = new MaskFormatter("#.###.###");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir o número do RG, "+erro);
        }
        tf_rg = tf_rg = new JFormattedTextField(formatoRg);
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        try
        {
            formatoFone = new MaskFormatter("(0xx##)####-####");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir o telefone Residencial"+erro);
        }
        tf_foneres = tf_foneres = new JFormattedTextField(formatoFone);
        jLabel16 = new javax.swing.JLabel();
        try
        {
            formatoFone = new MaskFormatter("(0xx##)####-####");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir o número de Telefone Celular"+erro);
        }
        tf_fonecom = tf_fonecom = new JFormattedTextField(formatoFone);
        jLabel17 = new javax.swing.JLabel();
        try
        {
            formatoFone = new MaskFormatter("(0xx##)####-####");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir o número de Telefone Celular"+erro);
        }
        tf_fonecel = tf_fonecel = new JFormattedTextField(formatoFone);
        jLabel18 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_obs = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_foto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        try
        {
            formatoCpf = new MaskFormatter("    ###.###.###-##");    
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel setar a mascara para cpf, "+erro);
        }
        tf_cpf = new JFormattedTextField(formatoCpf);
        try
        {
            formatoDataNasc = new MaskFormatter("    ##  /  ##  /  ####");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel setar a Data de Nascimento"+erro);
        }
        tf_datanasc = tf_datanasc = new JFormattedTextField(formatoDataNasc);
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        sexo_masc = new javax.swing.JRadioButton();
        sexo_fem = new javax.swing.JRadioButton();
        try
        {
            formatoDataCad = new MaskFormatter(" ## / ## / #### ");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir a data de cadastro"+erro);
        }
        tf_datacad = new JFormattedTextField(formatoDataCad);
        jLabel23 = new javax.swing.JLabel();

        setTitle("Cadastro de Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Código.:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Nome.:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Endereço.:");

        cb_logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_logradouroActionPerformed(evt);
            }
        });

        botao_primeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Rewind.png"))); // NOI18N
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Playback.png"))); // NOI18N
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Play.png"))); // NOI18N
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fast-forward.png"))); // NOI18N
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        botão_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        botão_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_gravarActionPerformed(evt);
            }
        });

        botao_inserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Create.png"))); // NOI18N
        botao_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_inserirActionPerformed(evt);
            }
        });

        botao_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Erase.png"))); // NOI18N
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Modify.png"))); // NOI18N
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Fone Reside.", "Fone Comer.", "Fone Cel", "E-Mail"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar.:");

        jcb_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Ordenação");

        grupo_ordenacao.add(rb_codigo);
        rb_codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_codigo.setText("Código");
        rb_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_codigoActionPerformed(evt);
            }
        });

        grupo_ordenacao.add(rb_nome);
        rb_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_nome.setSelected(true);
        rb_nome.setText("Nome");
        rb_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_nome)
                    .addComponent(jLabel3)
                    .addComponent(rb_codigo))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_nome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/View.png"))); // NOI18N
        jButton1.setText("Filtrar na Grade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("N°");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Complemento.:");

        tf_complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_complementoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Bairro.:");

        tf_codBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codBairroActionPerformed(evt);
            }
        });

        cb_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bairroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Cidade.:");

        tf_codCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codCidadeActionPerformed(evt);
            }
        });

        cb_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cidadeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Cep");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("RG.:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("CPF.:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Data Nasc.:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Fone Res.:");

        tf_foneres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneresActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Fone Com.:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Fone Cel.:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("E-Mail.:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Data Cadastro.:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Observação.:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Foto.:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        lbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BRIGHTS%20PRINTER_II.png"))); // NOI18N
        jButton3.setText("Impressão");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search.png"))); // NOI18N
        jButton4.setText("Consulta");

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setText("Sexo");

        grupo_sexo.add(sexo_masc);
        sexo_masc.setSelected(true);
        sexo_masc.setText("Masculino");
        sexo_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo_mascActionPerformed(evt);
            }
        });

        grupo_sexo.add(sexo_fem);
        sexo_fem.setText("Feminino");
        sexo_fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo_femActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sexo_masc))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sexo_fem)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sexo_masc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sexo_fem)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel23.setText("Cadastro de Funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(botao_primeiro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botao_anterior)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botao_proximo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botao_ultimo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botao_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botao_inserir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botao_excluir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botão_gravar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6)
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel18)))
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_codLog, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tf_codBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_codCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(5, 5, 5)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tf_obs, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_cpf)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_foneres, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_fonecom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_fonecel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tf_codLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_codBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(tf_codCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(tf_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cpf)
                            .addComponent(jLabel12))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_foneres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(tf_fonecom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(tf_fonecel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(tf_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botao_primeiro)
                        .addComponent(botao_anterior, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botao_proximo)
                        .addComponent(botao_ultimo))
                    .addComponent(botão_gravar)
                    .addComponent(botao_inserir)
                    .addComponent(botao_excluir)
                    .addComponent(botao_alterar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        setSize(new java.awt.Dimension(964, 692));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
 try
        {
           con_usuarios.resultset.next();
        
           mostrar_dados();
           navega = 2;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o próximo registro "+erro);
        }          
    }//GEN-LAST:event_botao_proximoActionPerformed

    private void botão_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_gravarActionPerformed
        // TODO add your handling code here:
        try
        {
            //insert int cidade (nome,uf) values ('Carazinho','RS')

            String sqlinsert ="insert into cliente " +
                    "(nome,logradouro,numero,complemento,bairro,cidade," +
                    "cep,RG,CPF,FoneRes,FoneCom,FoneCel,email,datanascimento," +
                    "sexo,datacadastro,foto,observacao) values ('"+
                    tf_nome.getText()+"','"+                    
                    tf_codLog.getText()+"','"+
                    tf_numero.getText()+"','"+
                    tf_complemento.getText()+"','"+
                    tf_codBairro.getText()+"','"+
                    tf_codCidade.getText()+"','"+
                    tf_cep.getText()+"','"+
                    tf_rg.getText()+"','"+
                    tf_cpf.getText()+"','"+
                    tf_foneres.getText()+"','"+
                    tf_fonecom.getText()+"','"+
                    tf_fonecel.getText()+"','"+
                    tf_email.getText()+"','"+
                    tf_datanasc.getText()+"','"+
                    sexo+"','"+
                    tf_datacad.getText()+"','"+
                    tf_foto.getText()+"','"+
                    tf_obs.getText()+"')";
                    
            con_usuarios.statement.executeUpdate(sqlinsert);         
            JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");

           //atualiza o ResultSet
           //con_usuarios.resultset = con_usuarios.statement.executeQuery("Select * from cidade");
           con_usuarios.executeSQL("select * from cliente order by "+ordenacao);
           atualiza_combo_box_cliente();
           con_usuarios.resultset.first(); //posiciona no primeiro registro
           mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        }
        catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro, existem campos em branco");
     }
        
    }//GEN-LAST:event_botão_gravarActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
         try
        {
           con_usuarios.resultset.first();
        
           mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o primeiro registro "+erro);
        }  
    }//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
         try
        {
           con_usuarios.resultset.last();
        
          mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o último registro "+erro);
        }  
    }//GEN-LAST:event_botao_ultimoActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
         try
        {
           con_usuarios.resultset.previous();
        
           mostrar_dados();
           navega = 1;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o registro anterior "+erro);
        }  
    }//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_inserirActionPerformed
        tf_codigo.setEditable(false);
        tf_nome.requestFocus();     
        tf_codLog.setText("");
        tf_numero.setText("");
        tf_complemento.setText("");
        tf_codBairro.setText("");
        tf_codigo.setText("");
        tf_cep.setText("");
        tf_rg.setText("");
        tf_cpf.setText("");
        tf_foneres.setText("");
        tf_fonecom.setText("");
        tf_fonecel.setText("");
        tf_email.setText("");
        tf_datanasc.setText("");
        
        Date data = new Date();
        String dia    = ""+data.getDate(); 
        String mes   = ""+String.valueOf(data.getMonth()+1); 
        String ano    = ""+(1900 + data.getYear());
        if (Integer.parseInt(mes)<=9)
            mes="0"+mes;
        tf_datacad.setText(dia+mes+ano);
        //********************************
        tf_obs.setText("");
        tf_foto.setText("semfoto.jpg");        
        lbFoto.setIcon(new ImageIcon("/MSI 1.0/imagens_clientes/"+tf_foto.getText()));
        tf_nome.requestFocus();
        tf_codigo.setEditable(false);
    }//GEN-LAST:event_botao_inserirActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        try
    {
      	String sql = "select * from cliente Where codigo = "+tf_codigo.getText();
   	con_usuarios.executeSQL(sql); 
        con_usuarios.resultset.first();
        String nome = "Deletar o Cliente : "+con_usuarios.resultset.getString("nome")+" ?";
        int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION)
   	{
   	    sql = "DELETE FROM cliente Where codigo ="+tf_codigo.getText();
  	    int conseguiu_excluir = con_usuarios.statement.executeUpdate(sql);
  	    if (conseguiu_excluir == 1)
            {
                JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                //atualiza o ResultSet
                con_usuarios.executeSQL("select * from cliente order by "+ordenacao);
                atualiza_combo_box_cliente();               
                con_usuarios.resultset.first(); //posiciona no primeiro registro
                mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
            }
         } 	
         else 
           return;  
    } 
    catch (SQLException erro)
    {
	JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
     }  
    }//GEN-LAST:event_botao_excluirActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
        try
    {
        String sql ="UPDATE cliente SET nome ='"+tf_nome.getText()+"',"+
                     "logradouro = '" +tf_codLog.getText()+"',"+
                    "numero = ' " +tf_numero.getText()+"',"+
                    "complemento = '" +tf_complemento.getText()+"',"+
                    "bairro = '" + tf_codBairro.getText()+"',"+
                    "cidade = '" + tf_codCidade.getText()+"',"+
                    "cep = '" + tf_cep.getText()+"',"+
                    "RG = '" + tf_rg.getText()+"',"+
                    "CPF = '" +tf_cpf.getText()+"',"+
                    "foneres = '" +tf_foneres.getText()+"',"+
                    "fonecom = '"  +tf_fonecom.getText()+"',"+
                    "fonecel = '"  +tf_fonecel.getText()+"',"+
                    "email = '"  +tf_email.getText()+"',"+
                    "datanascimento = '"  +tf_datanasc.getText()+"',"+
                    "sexo = '" +sexo+"',"+
                    "datacadastro = '"  +tf_datacad.getText()+"',"+
                    "foto = '"  +tf_foto.getText()+"',"+                    
                    "observacao = '"  +tf_obs.getText()+
                    "' where codigo = "+tf_codigo.getText();
        con_usuarios.statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Alteração realizado com sucesso!");
       
       //atualiza o ResultSet
       con_usuarios.executeSQL("select * from cliente order by "+ordenacao);
       atualiza_combo_box_cliente();
       con_usuarios.resultset.next(); //posiciona no primeiro registro
       mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
     }
  catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Alterar o registro..."+erro);
     }
    }//GEN-LAST:event_botao_alterarActionPerformed

    private void jcb_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_pesquisaActionPerformed
      if (inicia_combo == 1)
    {    
        try
         {
                con_usuarios.resultset.first();
                String igual = "n"; //inicia dizendo que não localizou a cidade                  
                while(igual == "n") //diz que enquanto não localizar é para ir executando
                {
                        if (con_usuarios.resultset.getString("nome").equals(jcb_pesquisa.getSelectedItem()))
                        {
                            igual = "s"; //indica que achou a cidade
                        }
                        else
                            con_usuarios.resultset.next(); //enquanto não achar vai para o proximo                   
                    }
                   // nas linhas abaxo, mostra_conteudo_tabela();
                  tf_codigo.setText(con_usuarios.resultset.getString("codigo"));//Essas duas linhas são necesárias                   
                   mostrar_dados();
               }
        catch(Exception erro)
        {
            //JOptionPane.showMessageDialog(null, "Não conseguiu localizar via Seleção no JComboBox, erro = "+erro);
        }
    }
    inicia_combo=1;
    }//GEN-LAST:event_jcb_pesquisaActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        try
        {
               con_usuarios.resultset.first();
               String igual = "n";
               int tamanho_pesquisa = tf_pesquisa.getText().length();
               while(igual == "n")
               {
                     String pesquisado = con_usuarios.resultset.getString("nome").substring(0,(tamanho_pesquisa));

                        if (pesquisado.equals(tf_pesquisa.getText()))
                        {
                             igual = "s";
                        }
                    else
                         con_usuarios.resultset.next();
                }                          
               // nas linhas abaxo, mostra_conteudo_tabela();
               tf_codigo.setText(con_usuarios.resultset.getString("codigo"));//Essas duas linhas é necesária                   
               mostrar_dados();                              
               jcb_pesquisa.setSelectedItem(tf_nome.getText());
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não conseguiu localizar via digitação, erro = "+erro);
        }
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    private void rb_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_codigoActionPerformed
        ordem_visualizacao("codigo");
    }//GEN-LAST:event_rb_codigoActionPerformed

    private void rb_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nomeActionPerformed
        ordem_visualizacao("nome");
    }//GEN-LAST:event_rb_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        con_usuarios.executeSQL("select * from cliente where nome like '"+tf_pesquisa.getText()+"%' order by "+ordenacao);          
          preencher_jtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_foneresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_foneresActionPerformed

    private void cb_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bairroActionPerformed
        // TODO add your handling code here:
        if (primeiraVezBairro == false)
    {    
        try
        {
            String sql = "select * from bairro Where nome like '"+cb_bairro.getSelectedItem()+"'";
            con_bairro.executeSQL(sql);
            con_bairro.resultset.first();
            tf_codBairro.setText(con_bairro.resultset.getString("codigo"));
         }
      
        catch (SQLException erro)
        {
            //JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
        }
   }
    primeiraVezBairro=false;
    
    }//GEN-LAST:event_cb_bairroActionPerformed

    private void tf_codBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codBairroActionPerformed

    private void cb_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cidadeActionPerformed
        // TODO add your handling code here:
        if (primeiraVezCidade == false)
    {    
        try
        {
            String sql = "select * from cidade Where nome like '"+cb_cidade.getSelectedItem()+"'";
            con_cidade.executeSQL(sql);
            con_cidade.resultset.first();
            tf_codCidade.setText(con_cidade.resultset.getString("codigo"));
         }
      
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
        }
    }
    primeiraVezCidade=false;
    }//GEN-LAST:event_cb_cidadeActionPerformed

    private void cb_logradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_logradouroActionPerformed
        if (primeiraVezLog == false)
    {    
        try
        {
            String sql = "select * from logradouro Where nome like '"+cb_logradouro.getSelectedItem()+"'";
            con_logradouro.executeSQL(sql);
            con_logradouro.resultset.first();
            tf_codLog.setText(con_logradouro.resultset.getString("codigo"));
         }
      
        catch (SQLException erro)
        {
            //JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
        }
   }
    primeiraVezLog=false;
    }//GEN-LAST:event_cb_logradouroActionPerformed

    private void tf_codCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codCidadeActionPerformed

    private void tf_complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_complementoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
    {
            JFileChooser busca_foto = new JFileChooser();
            busca_foto.setCurrentDirectory(new File("/MSI 1.0/imagens_clientes/"));        
            busca_foto.setDialogTitle("Carregar imagem do Cliente");         
            busca_foto.showOpenDialog(this);
            String foto = ""+busca_foto.getSelectedFile().getName();
            tf_foto.setText(foto);
            lbFoto.setIcon(new ImageIcon("/MSI 1.0/imagens_clientes/"+tf_foto.getText()));
    }        
    catch(Exception erro)
    {
        JOptionPane.showMessageDialog(null,"Nao foi possível carregar a foto.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sexo_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo_mascActionPerformed
        sexo="M";
    }//GEN-LAST:event_sexo_mascActionPerformed

    private void sexo_femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo_femActionPerformed
        sexo="F";
    }//GEN-LAST:event_sexo_femActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cad_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_inserir;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.JButton botão_gravar;
    private javax.swing.JComboBox cb_bairro;
    private javax.swing.JComboBox cb_cidade;
    private javax.swing.JComboBox cb_logradouro;
    private javax.swing.ButtonGroup grupo_ordenacao;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcb_pesquisa;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JRadioButton rb_codigo;
    private javax.swing.JRadioButton rb_nome;
    private javax.swing.JRadioButton sexo_fem;
    private javax.swing.JRadioButton sexo_masc;
    private javax.swing.JTextField tf_cep;
    private javax.swing.JTextField tf_codBairro;
    private javax.swing.JTextField tf_codCidade;
    private javax.swing.JTextField tf_codLog;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_complemento;
    private javax.swing.JFormattedTextField tf_cpf;
    private javax.swing.JFormattedTextField tf_datacad;
    private javax.swing.JFormattedTextField tf_datanasc;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fonecel;
    private javax.swing.JTextField tf_fonecom;
    private javax.swing.JTextField tf_foneres;
    private javax.swing.JTextField tf_foto;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_obs;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JTextField tf_rg;
    // End of variables declaration//GEN-END:variables

    
    public void mostrar_dados()
    {
         try
        {
           //con_usuarios.resultset.first();
        
           tf_codigo.setText(con_usuarios.resultset.getString("codigo"));
           tf_nome.setText(con_usuarios.resultset.getString("nome"));
           tf_codLog.setText(con_usuarios.resultset.getString("logradouro"));
           tf_numero.setText(con_usuarios.resultset.getString("numero"));
           tf_codBairro.setText(con_usuarios.resultset.getString("bairro"));
           tf_codCidade.setText(con_usuarios.resultset.getString("cidade"));
           tf_cep.setText(con_usuarios.resultset.getString("cep"));            
           tf_rg.setText(con_usuarios.resultset.getString("rg"));
           tf_cpf.setText(con_usuarios.resultset.getString("CPF"));
           tf_foneres.setText(con_usuarios.resultset.getString("FoneRes"));
           tf_fonecom.setText(con_usuarios.resultset.getString("FoneCom"));
           tf_fonecel.setText(con_usuarios.resultset.getString("FoneCel"));
           tf_email.setText(con_usuarios.resultset.getString("Email"));
           tf_datanasc.setText(con_usuarios.resultset.getString("DataNascimento"));
           tf_datacad.setText(con_usuarios.resultset.getString("DataCadastro"));
           tf_obs.setText(con_usuarios.resultset.getString("Observacao"));
           tf_complemento.setText(con_usuarios.resultset.getString("complemento"));  
           tf_foto.setText(con_usuarios.resultset.getString("foto"));
           lbFoto.setIcon(new ImageIcon("/MSI 1.0/imagens_clientes/"+tf_foto.getText()));
           atualizaComboBoxBairro();
           atualizaComboBoxCid();
           atualizaComboBoxLog();
           if (con_usuarios.resultset.getString("sexo").equals("M"))
                sexo_masc.setSelected(true);
           else
                sexo_fem.setSelected(true);
        }
        catch(SQLException erro)
        {
            if (navega == 1)
                JOptionPane.showMessageDialog(null,"Você já está no primeiro registro");
            else if (navega == 2)
                 JOptionPane.showMessageDialog(null,"Você já está no último registro");
            else
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }  
    }
    public void atualiza_combo_box_cliente()
    {
        try
        {
          jcb_pesquisa.removeAllItems();
          con_usuarios.executeSQL("select * from cliente order by "+ordenacao);
          while(con_usuarios.resultset.next())
              jcb_pesquisa.addItem(con_usuarios.resultset.getString("nome"));           
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }

    }
    public void preencher_jtable()
    {
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(200);
        con_usuarios.executeSQL("select * from cliente where nome like '"+tf_pesquisa.getText()+"%' order by "+ordenacao);
         
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
         
        try
        {
            
            while (con_usuarios.resultset.next())
                modelo.addRow(new Object [] {con_usuarios.resultset.getString("Codigo"),con_usuarios.resultset.getString("nome"),con_usuarios.resultset.getString("foneres"),con_usuarios.resultset.getString("fonecom"),con_usuarios.resultset.getString("fonecel"),con_usuarios.resultset.getString("email")});
            con_usuarios.resultset.first();
        }
catch (SQLException erro){
    JOptionPane.showMessageDialog(null,"Erro ao listar no JTable "+erro);
}
    }
    public void ordem_visualizacao(String Ordem)
    {
        ordenacao = Ordem;
        con_usuarios.executeSQL("select * from cliente  order by "+ordenacao);           
        preencher_jtable();
        atualiza_combo_box_cliente();
        try
        {
            con_usuarios.resultset.first();
        }
         catch (SQLException erro){
             JOptionPane.showMessageDialog(null,"Erro na ordenação dos dados "+erro);
        }
        mostrar_dados();
        
    }
    public void atualizaComboBoxBairro()
    {
    // procedimento para atualizar jcombobox de bairro
    try
        {
            String sql = "select * from bairro Where codigo ="+tf_codBairro.getText();
            con_bairro.executeSQL(sql);
            con_bairro.resultset.first();
            cb_bairro.setSelectedItem(con_bairro.resultset.getString("nome"));
         }
      
        catch (SQLException erro)
        {
                JOptionPane.showMessageDialog(null,"Nao foi possivel localizar bairro");
                tf_codBairro.requestFocus();

        }
   

    }
    public void atualizaComboBoxCid()
    {
    // procedimento para atualizar jcombobox de cidade
    try
        {
            String sql = "select * from cidade Where codigo ="+tf_codCidade.getText();
            con_cidade.executeSQL(sql);
            con_cidade.resultset.first();
            cb_cidade.setSelectedItem(con_cidade.resultset.getString("nome"));
         }
      
        catch (SQLException erro)
        {
                JOptionPane.showMessageDialog(null,"Nao foi possivel localizar cidade");
                tf_codCidade.requestFocus();
        }
   

    }
    public void atualizaComboBoxLog()
    {
    // procedimento para atualizar jcombobox de log
    try
        {
            String sql = "select * from logradouro Where codigo ="+tf_codLog.getText();
            con_logradouro.executeSQL(sql);
            con_logradouro.resultset.first();
            cb_logradouro.setSelectedItem(con_logradouro.resultset.getString("nome"));
         }
      
        catch (SQLException erro)
        {
                JOptionPane.showMessageDialog(null,"Nao foi possivel localizar Logradouro");
                tf_codLog.requestFocus();

        }
   

    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconTela.png")));
    }
}