/*
 * Copyright (C) 2022 Adriano Silva
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cadastros;

/**
 *
 * @author Adriano Silva
 */
import java.sql.SQLException;
import java.util.Date;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.conexao;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Adriano Silva
 */
public final class cad_estoque extends javax.swing.JFrame {
    
    MaskFormatter formatoValor,formatoFone,formatoData;
    int navega = 0;
    int inicia_combo =0;
    String ordenacao="produto",situacao="M";
    boolean primeiraVezTipo=true,primeiraVezCliente=true,primeiraVezFornecedor=true;
    conexao con_usuarios,con_estoque,con_tipo,con_fornecedor;
    
    /**
     *
     */
    public cad_estoque() {
        
        initComponents();
        con_usuarios = new conexao();
        con_usuarios.conecta();
        
        con_tipo=new conexao();
        con_tipo.conecta();
        
        con_fornecedor=new conexao();
        con_fornecedor.conecta();
        
        con_estoque=new conexao();
        con_estoque.conecta();
        
        con_estoque.executeSQL("select * from estoque order by "+ordenacao);
        con_usuarios.executeSQL("select * from cliente order by nome");
        con_tipo.executeSQL("select * from tipo order by nome");
        con_fornecedor.executeSQL("select * from fornecedor order by nome");  
       
        try
        {
            while(con_estoque.resultset.next())
                jcb_pesquisa.addItem(con_estoque.resultset.getString("produto"));
            
            while(con_usuarios.resultset.next())
                {
                    cb_cliente.addItem(con_usuarios.resultset.getString("nome"));
                }
                
            while(con_tipo.resultset.next())
                cb_tipo.addItem(con_tipo.resultset.getString("nome"));
            while (con_fornecedor.resultset.next())
                 cb_fornecedor.addItem(con_fornecedor.resultset.getString("nome"));
            
            
            con_estoque.resultset.first();
            mostrar_dados();
           
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }  
        
        preencher_jtable();//chama metod para preencher a Tabela das Cidades
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_ordenacao = new javax.swing.ButtonGroup();
        grupo_sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_produto = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox();
        botao_primeiro = new javax.swing.JButton();
        botao_anterior = new javax.swing.JButton();
        botao_proximo = new javax.swing.JButton();
        botao_ultimo = new javax.swing.JButton();
        botão_gravar = new javax.swing.JButton();
        botao_inserir = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tf_pesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcb_pesquisa = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rb_codigo = new javax.swing.JRadioButton();
        rb_nome = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        tf_tipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_unidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_quantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_precocusto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_percentual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_precovenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_qtdMinima = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_codcli = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_codfor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_dataultvend = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_dataultcomp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_foto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tf_qtdMaxima = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        situ_ativo = new javax.swing.JRadioButton();
        situ_inativo = new javax.swing.JRadioButton();
        try
        {
            formatoData = new MaskFormatter(" ## / ## / #### ");
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir a data de cadastro"+erro);
        }
        tf_datacad = new JFormattedTextField(formatoData);
        cb_cliente = new javax.swing.JComboBox();
        cb_fornecedor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tf_obs = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setTitle("Estoque");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_estoque.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Código.:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Produto.:");

        cb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoActionPerformed(evt);
            }
        });

        botao_primeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Rewind.png"))); // NOI18N
        botao_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroActionPerformed(evt);
            }
        });

        botao_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Playback.png"))); // NOI18N
        botao_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_anteriorActionPerformed(evt);
            }
        });

        botao_proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Play.png"))); // NOI18N
        botao_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_proximoActionPerformed(evt);
            }
        });

        botao_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fast-forward.png"))); // NOI18N
        botao_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ultimoActionPerformed(evt);
            }
        });

        botão_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        botão_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_gravarActionPerformed(evt);
            }
        });

        botao_inserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Create.png"))); // NOI18N
        botao_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_inserirActionPerformed(evt);
            }
        });

        botao_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Erase.png"))); // NOI18N
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        botao_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Modify.png"))); // NOI18N
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome do Produto", "Quantidade", "Preço Custo", "Preço Venda", "Disponibilidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar.:");

        jcb_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Ordenação");

        grupo_ordenacao.add(rb_codigo);
        rb_codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_codigo.setText("Código");
        rb_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_codigoActionPerformed(evt);
            }
        });

        grupo_ordenacao.add(rb_nome);
        rb_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_nome.setSelected(true);
        rb_nome.setText("Nome");
        rb_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_nome)
                    .addComponent(jLabel3)
                    .addComponent(rb_codigo))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_nome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/View.png"))); // NOI18N
        jButton1.setText("Filtrar na Grade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tf_tipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_tipoFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Unidade.:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Quantidade.:");

        tf_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_quantidadeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Preço de Custo.:");

        tf_precocusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_precocustoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Percentual Lucro.:");

        tf_percentual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_percentualFocusLost(evt);
            }
        });
        tf_percentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_percentualActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Preço de Venda.:");

        tf_precovenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_precovendaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Quantidade Mínima.:");

        tf_qtdMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_qtdMinimaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Quantidade Máxima.:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Último Cliente.:");

        tf_codcli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_codcliFocusLost(evt);
            }
        });
        tf_codcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codcliActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Último Fornecedor.:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Data última venda.:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Data da última Compra.:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Data Cadastro.:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Foto.:");

        tf_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fotoActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BRIGHTS%20PRINTER_II.png"))); // NOI18N
        jButton3.setText("Impressão");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search.png"))); // NOI18N
        jButton4.setText("Consulta");

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Situação");

        grupo_sexo.add(situ_ativo);
        situ_ativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        situ_ativo.setSelected(true);
        situ_ativo.setText("Disponível");
        situ_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situ_ativoActionPerformed(evt);
            }
        });

        grupo_sexo.add(situ_inativo);
        situ_inativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        situ_inativo.setText("Indisponível");
        situ_inativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situ_inativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(situ_ativo)
                    .addComponent(situ_inativo)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(situ_ativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(situ_inativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_clienteActionPerformed(evt);
            }
        });

        cb_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fornecedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Obs.:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Tipo.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_dataultcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_dataultvend, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_qtdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_qtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_precocusto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_percentual, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_precovenda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(348, 348, 348)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_codcli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_codfor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(tf_obs, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(botao_primeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_proximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_ultimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_inserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botão_gravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_produto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tf_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_precocusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf_percentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_precovenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_qtdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_qtdMaxima)
                    .addComponent(jLabel19)
                    .addComponent(tf_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_codcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tf_codfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_dataultcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tf_dataultvend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel5)
                    .addComponent(tf_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botao_primeiro)
                        .addComponent(botao_anterior, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botao_proximo)
                        .addComponent(botao_ultimo))
                    .addComponent(botão_gravar)
                    .addComponent(botao_inserir)
                    .addComponent(botao_excluir)
                    .addComponent(botao_alterar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        setSize(new java.awt.Dimension(964, 692));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_proximoActionPerformed
 try
        {
           con_usuarios.resultset.next();
        
           mostrar_dados();
           navega = 2;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o próximo registro "+erro);
        }          
    }//GEN-LAST:event_botao_proximoActionPerformed

    private void botão_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_gravarActionPerformed
        // TODO add your handling code here:
        try
        {
            

            String sqlinsert ="insert into estoque " +
                    "(produto,unidade,tipo,quantidade,precoCusto,percentual,precoVenda," +
                    "qtdMinima, qtdMaxima, ultCliente, ultFornecedor,dataCadastro,"+
                    "dataUltVenda,dataUltCompra,obs,situacao) values ('"+
                    tf_produto.getText()+"','"+
                    tf_unidade.getText()+"','"+
                    tf_tipo.getText()+"','"+
                    tf_quantidade.getText()+"','"+
                    tf_precocusto.getText()+"','"+
                    tf_percentual.getText()+"','"+
                    tf_precovenda.getText()+"','"+
                    tf_qtdMinima.getText()+"','"+
                    tf_qtdMaxima.getText()+"','"+
                    tf_codcli.getText()+"','"+
                    tf_codfor.getText()+"','"+
                    tf_datacad.getText()+"','"+
                    tf_dataultvend.getText()+"','"+
                    tf_dataultcomp.getText()+"','"+
                    situacao+"','"+
                    tf_foto.getText()+"','"+
                    tf_obs.getText()+"')";
                    JOptionPane.showMessageDialog(null,"sql = "+sqlinsert);
                    con_estoque.statement.executeUpdate(sqlinsert);
                    JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");           
                    //atualiza o ResultSet
                    
                    con_estoque.executeSQL("select * from estoque  order by "+ordenacao);
                    atualizaComboBoxEstoque();
                    con_estoque.resultset.first(); //posiciona no primeiro registro
                    mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        }
        catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro, existem campos em branco");
     }
        
    }//GEN-LAST:event_botão_gravarActionPerformed

    private void botao_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroActionPerformed
         try
        {
           con_usuarios.resultset.first();
        
           mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o primeiro registro "+erro);
        }  
    }//GEN-LAST:event_botao_primeiroActionPerformed

    private void botao_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ultimoActionPerformed
         try
        {
           con_usuarios.resultset.last();
        
          mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o último registro "+erro);
        }  
    }//GEN-LAST:event_botao_ultimoActionPerformed

    private void botao_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_anteriorActionPerformed
         try
        {
           con_usuarios.resultset.previous();
        
           mostrar_dados();
           navega = 1;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o registro anterior "+erro);
        }  
    }//GEN-LAST:event_botao_anteriorActionPerformed

    private void botao_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_inserirActionPerformed
        
        
        tf_codigo.setText("");
        tf_produto.setText("");
        tf_unidade.setText("");
        tf_quantidade.setText("");
        tf_precocusto.setText("");
        tf_percentual.setText("");
        tf_precovenda.setText("");
        tf_qtdMinima.setText("");
        tf_qtdMaxima.setText("");
        tf_datacad.setText("");
        tf_dataultcomp.setText("");
        tf_dataultvend.setText("");
        tf_obs.setText("");
        tf_codcli.setText("");
        tf_codfor.setText("");
        //rorina par inserir data atual ao novo registro
        Date data = new Date();
        String dia    = ""+data.getDate();
        String mes   = ""+String.valueOf(data.getMonth()+1);
        String ano    = ""+(1900 + data.getYear());
        if (Integer.parseInt(mes)<=9)
            mes="0"+mes;
        tf_datacad.setText(dia+mes+ano);
        //********************************
        tf_obs.setText("");
        tf_foto.setText("semfoto.jpg");
        tf_produto.requestFocus();
        tf_codigo.setEditable(false);
    }//GEN-LAST:event_botao_inserirActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        try
    {
      	String sql = "select * from estoque Where codigo = "+tf_codigo.getText();
   	con_usuarios.executeSQL(sql); 
        con_usuarios.resultset.first();
        String nome = "Deletar o Produto : "+con_estoque.resultset.getString("produto")+" ?";
        int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION)
   	{
   	    sql = "DELETE FROM estoque Where codigo ="+tf_codigo.getText();
  	    int conseguiu_excluir = con_usuarios.statement.executeUpdate(sql);
  	    if (conseguiu_excluir == 1)
            {
                JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                //atualiza o ResultSet
                con_usuarios.executeSQL("select * from estoque order by "+ordenacao);
                atualiza_combo_box_cliente();               
                con_usuarios.resultset.first(); //posiciona no primeiro registro
                mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
            }
         } 	
         else 
           return;  
    } 
    catch (SQLException erro)
    {
	JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
     }  
    }//GEN-LAST:event_botao_excluirActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
         try
        {
            String sql ="UPDATE estoque SET produto ='"+tf_produto.getText()+"',"+
                    "unidade = '" +tf_unidade.getText()+"',"+
                    "tipo = ' " +tf_tipo.getText()+"',"+
                    "quantidade = '" +tf_quantidade.getText()+"',"+
                    "precoCusto = '" + tf_precocusto.getText()+"',"+
                    "percentual = '" + tf_percentual.getText()+"',"+
                    "precoVenda = '" + tf_precovenda.getText()+"',"+
                    "qtdMinima = '" + tf_qtdMinima.getText()+"',"+
                    "qtdMaxima = '" + tf_qtdMaxima.getText()+"',"+
                    "ultCliente = '" +tf_codcli.getText()+"',"+
                    "ultFornecedor = '"  +tf_codfor.getText()+"',"+
                    "datacadastro = '"  +tf_datacad.getText()+"',"+
                    "dataUltVenda = '"  +tf_dataultvend.getText()+"',"+
                    "dataUltCompra = '"  +tf_dataultcomp.getText()+"',"+
                    "situacao = '"  +situacao+"',"+
                    "foto = '"  +tf_foto.getText()+"',"+
                    "obs = '"  +tf_obs.getText()+
                    "' where codigo = "+tf_codigo.getText();
            
            con_estoque.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Alteração realizado com sucesso!");
            
            //atualiza o ResultSet
            con_estoque.executeSQL("Select * from estoque  order by "+ordenacao);
            atualizaComboBoxEstoque();
            con_estoque.resultset.next(); //posiciona no primeiro registro
            mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        }
catch (SQLException erro)
{
    JOptionPane.showMessageDialog(null,"Erro a tentar Alterar o registro..."+erro);
}
    }//GEN-LAST:event_botao_alterarActionPerformed

    private void jcb_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_pesquisaActionPerformed
      if (inicia_combo == 1)
    {    
        try
         {
                con_usuarios.resultset.first();
                String igual = "n"; //inicia dizendo que não localizou a cidade                  
                while(igual == "n") //diz que enquanto não localizar é para ir executando
                {
                        if (con_usuarios.resultset.getString("nome").equals(jcb_pesquisa.getSelectedItem()))
                        {
                            igual = "s"; //indica que achou a cidade
                        }
                        else
                            con_usuarios.resultset.next(); //enquanto não achar vai para o proximo                   
                    }
                   // nas linhas abaxo, mostra_conteudo_tabela();
                  tf_codigo.setText(con_usuarios.resultset.getString("codigo"));//Essas duas linhas são necesárias                   
                   mostrar_dados();
               }
        catch(SQLException erro)
        {
            //JOptionPane.showMessageDialog(null, "Não conseguiu localizar via Seleção no JComboBox, erro = "+erro);
        }
    }
    inicia_combo=1;
    }//GEN-LAST:event_jcb_pesquisaActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        try
        {
               con_usuarios.resultset.first();
               String igual = "n";
               int tamanho_pesquisa = tf_pesquisa.getText().length();
               while("n".equals(igual))
               {
                     String pesquisado = con_usuarios.resultset.getString("nome").substring(0,(tamanho_pesquisa));

                        if (pesquisado.equals(tf_pesquisa.getText()))
                        {
                             igual = "s";
                        }
                    else
                         con_usuarios.resultset.next();
                }                          
               // nas linhas abaxo, mostra_conteudo_tabela();
               tf_codigo.setText(con_usuarios.resultset.getString("codigo"));//Essas duas linhas é necesária                   
               mostrar_dados();                              
               jcb_pesquisa.setSelectedItem(tf_produto.getText());
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não conseguiu localizar via digitação, erro = "+erro);
        }
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    private void rb_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_codigoActionPerformed
        ordem_visualizacao("codigo");
    }//GEN-LAST:event_rb_codigoActionPerformed

    private void rb_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nomeActionPerformed
        ordem_visualizacao("produto");
    }//GEN-LAST:event_rb_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       con_estoque.executeSQL("select * from estoque where produto like '"+tf_pesquisa.getText()+"%' order by "+ordenacao);
        preencher_jtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_codcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codcliActionPerformed

    private void tf_precocustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_precocustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_precocustoActionPerformed

    private void cb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoActionPerformed
      
        if (primeiraVezTipo == false)
    {    
        try
            {
                String sql = "select * from tipo Where nome like '"+cb_tipo.getSelectedItem()+"'";
                con_tipo.executeSQL(sql);
                con_tipo.resultset.first();
                tf_tipo.setText(con_tipo.resultset.getString("codigo"));
            }          
           catch (SQLException erro)
           {
                //JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
            }
        }
        primeiraVezTipo=false;
    }//GEN-LAST:event_cb_tipoActionPerformed

    private void tf_percentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_percentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_percentualActionPerformed

    private void tf_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_quantidadeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
    {
            JFileChooser busca_foto = new JFileChooser();
            busca_foto.setCurrentDirectory(new File("C:\\Idea Tecnologia\\img estoque\\"));        
            busca_foto.setDialogTitle("Carregar imagem do Cliente");         
            busca_foto.showOpenDialog(this);
            String foto = ""+busca_foto.getSelectedFile().getName();
            tf_foto.setText(foto);
            //lbFoto.setIcon(new ImageIcon("/MSI 1.0/imagens_clientes/"+tf_foto.getText()));
    }        
    catch(Exception erro)
    {
        JOptionPane.showMessageDialog(null,"Nao foi possível carregar a foto.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void situ_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situ_ativoActionPerformed
        situacao="A";
    }//GEN-LAST:event_situ_ativoActionPerformed

    private void situ_inativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situ_inativoActionPerformed
        situacao="I";
    }//GEN-LAST:event_situ_inativoActionPerformed

    private void tf_percentualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_percentualFocusLost
        double pv;
        pv = ((Double.parseDouble(tf_precocusto.getText()) *
              Double.parseDouble(tf_percentual.getText())) / 100)  +
              Double.parseDouble(tf_precocusto.getText()); 
        tf_precovenda.setText(String.valueOf(pv));
    }//GEN-LAST:event_tf_percentualFocusLost

    private void cb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_clienteActionPerformed
       if (primeiraVezCliente == false)
        {
            try
            {
                String sql = "select * from cliente Where nome like '"+cb_cliente.getSelectedItem()+"'";
                con_usuarios.executeSQL(sql);
                con_usuarios.resultset.first();
                tf_codcli.setText(con_usuarios.resultset.getString("codigo"));
            }          
           catch (SQLException erro)
           {
                JOptionPane.showMessageDialog(null,"Erro a tentar CLIENTES COMBOBOX..."+erro);
            }
        }
        primeiraVezCliente=false;
    }//GEN-LAST:event_cb_clienteActionPerformed

    private void cb_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fornecedorActionPerformed
       if (primeiraVezFornecedor == false)
        {
            try
            {
                String sql = "select * from fornecedor Where nome like '"+cb_fornecedor.getSelectedItem()+"'";
                con_fornecedor.executeSQL(sql);
                con_fornecedor.resultset.first();
                tf_codfor.setText(con_fornecedor.resultset.getString("codigo"));
            }          
           catch (SQLException erro)
           {
                    JOptionPane.showMessageDialog(null,"Erro a tentar FORNECEDOR COMBOBOX..."+erro);
            }
        }
        primeiraVezFornecedor=false;
    }//GEN-LAST:event_cb_fornecedorActionPerformed

    private void tf_tipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_tipoFocusLost
        atualizaComboBoxTipo();
    }//GEN-LAST:event_tf_tipoFocusLost

    private void tf_codcliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_codcliFocusLost
         atualiza_combo_box_cliente();
       
    }//GEN-LAST:event_tf_codcliFocusLost

    private void tf_precovendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_precovendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_precovendaActionPerformed

    private void tf_qtdMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_qtdMinimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_qtdMinimaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cad_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cad_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cad_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cad_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cad_estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_anterior;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_inserir;
    private javax.swing.JButton botao_primeiro;
    private javax.swing.JButton botao_proximo;
    private javax.swing.JButton botao_ultimo;
    private javax.swing.JButton botão_gravar;
    private javax.swing.JComboBox cb_cliente;
    private javax.swing.JComboBox cb_fornecedor;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.ButtonGroup grupo_ordenacao;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcb_pesquisa;
    private javax.swing.JRadioButton rb_codigo;
    private javax.swing.JRadioButton rb_nome;
    private javax.swing.JRadioButton situ_ativo;
    private javax.swing.JRadioButton situ_inativo;
    private javax.swing.JTextField tf_codcli;
    private javax.swing.JTextField tf_codfor;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JFormattedTextField tf_datacad;
    private javax.swing.JTextField tf_dataultcomp;
    private javax.swing.JTextField tf_dataultvend;
    private javax.swing.JTextField tf_foto;
    private javax.swing.JTextField tf_obs;
    private javax.swing.JTextField tf_percentual;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JTextField tf_precocusto;
    private javax.swing.JTextField tf_precovenda;
    private javax.swing.JTextField tf_produto;
    private javax.swing.JFormattedTextField tf_qtdMaxima;
    private javax.swing.JTextField tf_qtdMinima;
    private javax.swing.JTextField tf_quantidade;
    private javax.swing.JTextField tf_tipo;
    private javax.swing.JTextField tf_unidade;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void mostrar_dados()
    {
         try
        {
           
            tf_codigo.setText(con_estoque.resultset.getString("codigo"));
            tf_produto.setText(con_estoque.resultset.getString("produto"));
            tf_unidade.setText(con_estoque.resultset.getString("unidade"));
            tf_tipo.setText(con_estoque.resultset.getString("tipo"));
            tf_quantidade.setText(con_estoque.resultset.getString("quantidade"));
            tf_precocusto.setText(con_estoque.resultset.getString("precocusto"));
            tf_percentual.setText(con_estoque.resultset.getString("percentual"));
            tf_precovenda.setText(con_estoque.resultset.getString("precovenda"));
            tf_qtdMinima.setText(con_estoque.resultset.getString("qtdminima"));
            tf_qtdMaxima.setText(con_estoque.resultset.getString("qtdmaxima"));
            tf_datacad.setText(con_estoque.resultset.getString("datacadastro"));
            tf_dataultcomp.setText(con_estoque.resultset.getString("dataultcompra"));
            tf_dataultvend.setText(con_estoque.resultset.getString("dataultvenda"));
            tf_codcli.setText(con_estoque.resultset.getString("ultCliente"));
            tf_codfor.setText(con_estoque.resultset.getString("ultFornecedor"));
            tf_foto.setText(con_estoque.resultset.getString("foto"));
            atualizaComboBoxTipo();
            atualiza_combo_box_cliente();
            atualizaComboBoxFornecedor();
            if (con_estoque.resultset.getString("situacao").equals("A"))
                situ_ativo.setSelected(true);
            else
                situ_inativo.setSelected(true);
        }
        catch(SQLException erro)
        {
            if (navega == 1)
                JOptionPane.showMessageDialog(null,"Você já está no primeiro registro");
            else if (navega == 2)
                 JOptionPane.showMessageDialog(null,"Você já está no último registro");
            else
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }  
    }

    /**
     *
     */
    public void atualiza_combo_box_cliente()
    {
        try
        {
           String sql = "select * from cliente Where codigo ="+tf_codcli.getText();
            con_usuarios.executeSQL(sql);
            con_usuarios.resultset.first();
            cb_cliente.setSelectedItem(con_usuarios.resultset.getString("nome"));
        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Nao foi possivel localizar cliente");
            tf_codcli.requestFocus();
        }

    }

    /**
     *
     */
    public void preencher_jtable()
   {
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
        con_estoque.executeSQL("select * from estoque where produto like '"+tf_pesquisa.getText()+"%' order by "+ordenacao);        
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);        
        try
        {           
            while (con_estoque.resultset.next())
                modelo.addRow(new Object [] {con_estoque.resultset.getString("Codigo"),con_estoque.resultset.getString("produto"),con_estoque.resultset.getString("quantidade"),con_estoque.resultset.getString("precocusto"),con_estoque.resultset.getString("precovenda"),con_estoque.resultset.getString("situacao")});
            con_estoque.resultset.first();
        }
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Erro ao listar no JTable "+erro);
        }
    }

    /**
     *
     * @param Ordem
     */
    public void ordem_visualizacao(String Ordem)
    {
        ordenacao = Ordem;
        con_estoque.executeSQL("select * from estoque  order by "+ordenacao);           
        preencher_jtable();
        atualiza_combo_box_cliente();
        try
        {
            con_estoque.resultset.first();
        }
         catch (SQLException erro){
             JOptionPane.showMessageDialog(null,"Erro na ordenação dos dados "+erro);
        }
        mostrar_dados();
        
    }

    /**
     *
     */
    public void atualizaComboBoxFornecedor()
   {
        // procedimento para atualizar jcombobox de fornecedor
        try
        {
            String sql = "select * from fornecedor Where codigo ="+tf_codfor.getText();
            con_fornecedor.executeSQL(sql);
            con_fornecedor.resultset.first();
            cb_fornecedor.setSelectedItem(con_fornecedor.resultset.getString("nome"));
        }
        
        catch (SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Nao foi possivel localizar bairro");
            tf_codfor.requestFocus();
            
        }
        
        
    }

    /**
     *
     */
    public void atualizaComboBoxTipo()
   {
        // procedimento para atualizar jcombobox de log
        try
        {
            String sql = "select * from tipo Where codigo ="+tf_tipo.getText();
            con_tipo.executeSQL(sql);
            con_tipo.resultset.first();
            cb_tipo.setSelectedItem(con_tipo.resultset.getString("nome"));
        }
        
        catch (SQLException erro)
       {  
            JOptionPane.showMessageDialog(null,"Nao foi possivel localizar Tipo");
            tf_tipo.requestFocus();
            
        }
        
        
    }

    /**
     *
     */
    public void atualizaComboBoxEstoque()
   {
      try
        {
            jcb_pesquisa.removeAllItems();
            con_estoque.executeSQL("select * from estoque order by "+ordenacao);
            while(con_estoque.resultset.next())
                jcb_pesquisa.addItem(con_estoque.resultset.getString("produto"));
        }
             catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
   }
      
    
}